version: '3.1'

services:

  db:
    image: mysql:9.2
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql/db:/var/lib/mysql
      - ./.docker/mysql/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
    env_file:
      - .env

  redis:
    image: redis:7.4-alpine
    container_name: redis
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - ./.docker/redis_data:/data
    env_file:
      - .env
