installpath="/var/www/html";
installpath1=$(echo "$installpath" | sed 's/\//\\\//g');
read -p "MySQL Root Username: " mysqluser;
echo "MySQL Root Password:";
read -s mysqlpass;
sudo git clone https://github.com/wil-ldf-ire/server-wildfire.git $installpath;
sudo sed -i "s/mysql_root_user/$mysqluser/g" $installpath/server.sh;
sudo sed -i "s/mysql_root_pass/$mysqlpass/g" $installpath/server.sh;
sudo bash $installpath/server.sh;
sudo rm $installpath/server.sh;
sudo rm $installpath/install.sh;