DEBIAN_FRONTEND=noninteractive apt -yq update;
DEBIAN_FRONTEND=noninteractive apt -yq upgrade;
DEBIAN_FRONTEND=noninteractive apt-get -yq install lsb-release ca-certificates apt-transport-https software-properties-common;
ufw allow OpenSSH;
ufw allow Postfix;
ufw allow 80;
ufw allow 8080;
ufw allow 3000;
ufw allow 443;
ufw allow 587;
yes | ufw enable;
DEBIAN_FRONTEND=noninteractive apt-get -yq install git;
DEBIAN_FRONTEND=noninteractive apt-get -yq install mysql-server;
DEBIAN_FRONTEND=noninteractive apt-get -yq install php;
DEBIAN_FRONTEND=noninteractive apt-get -yq install php-cli;
DEBIAN_FRONTEND=noninteractive apt-get -yq install php-fpm;
DEBIAN_FRONTEND=noninteractive apt-get -yq install php-mysql;
DEBIAN_FRONTEND=noninteractive apt-get -yq install php-curl;
DEBIAN_FRONTEND=noninteractive apt-get -yq install php-mbstring;
DEBIAN_FRONTEND=noninteractive apt-get -yq install php-mysql;
DEBIAN_FRONTEND=noninteractive apt-get -yq install php-curl;
DEBIAN_FRONTEND=noninteractive apt-get -yq install php-gd;
DEBIAN_FRONTEND=noninteractive apt-get -yq install php-zip;
DEBIAN_FRONTEND=noninteractive apt-get -yq install php-xml;
php_ver="$(cut -d '.' -f 1 <<< "$(php -r "echo phpversion();")")"."$(cut -d '.' -f 2 <<< "$(php -r "echo phpversion();")")";
DEBIAN_FRONTEND=noninteractive apt-get -yq install net-tools;
DEBIAN_FRONTEND=noninteractive apt-get -yq install zip;
DEBIAN_FRONTEND=noninteractive apt-get -yq install unzip;
DEBIAN_FRONTEND=noninteractive apt-get -yq install p7zip-full;
DEBIAN_FRONTEND=noninteractive apt-get -yq install nginx;
DEBIAN_FRONTEND=noninteractive apt-get -yq install build-essential;
DEBIAN_FRONTEND=noninteractive apt-get -yq install curl;
DEBIAN_FRONTEND=noninteractive apt-get -yq install s3cmd;
DEBIAN_FRONTEND=noninteractive apt-get -yq install htop;
DEBIAN_FRONTEND=noninteractive apt-get -yq install poppler-utils;
DEBIAN_FRONTEND=noninteractive apt-get -yq install python3-pip;
DEBIAN_FRONTEND=noninteractive apt-get -yq install imagemagick;
DEBIAN_FRONTEND=noninteractive apt-get -yq install ffmpeg;
DEBIAN_FRONTEND=noninteractive echo 'post_max_size = 1024M' | tee -a /etc/php/$php_ver/fpm/php.ini;
DEBIAN_FRONTEND=noninteractive echo 'upload_max_filesize = 1024M' | tee -a /etc/php/$php_ver/fpm/php.ini;
DEBIAN_FRONTEND=noninteractive echo 'memory_limit = 2048M' | tee -a /etc/php/$php_ver/fpm/php.ini;
yes | curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php;
yes | php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer;
yes | systemctl disable --now apache2;
DEBIAN_FRONTEND=noninteractive echo "ALTER USER 'mysql_root_user'@'localhost' IDENTIFIED WITH mysql_native_password BY 'mysql_root_pass'; FLUSH PRIVILEGES; exit;" | mysql;
DEBIAN_FRONTEND=noninteractive echo 'expire_logs_days = 3' | tee -a /etc/mysql/mysql.conf.d/mysqld.cnf;
DEBIAN_FRONTEND=noninteractive echo 'binlog_expire_logs_seconds = 86400' | tee -a /etc/mysql/mysql.conf.d/mysqld.cnf;
DEBIAN_FRONTEND=noninteractive snap install --classic certbot;
DEBIAN_FRONTEND=noninteractive apt-get -yq install python3-certbot-nginx;
DEBIAN_FRONTEND=noninteractive /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024;
DEBIAN_FRONTEND=noninteractive /sbin/mkswap /var/swap.1;
DEBIAN_FRONTEND=noninteractive /sbin/swapon /var/swap.1;
DEBIAN_FRONTEND=noninteractive service php$php_ver-fpm restart;
DEBIAN_FRONTEND=noninteractive apt -yq update;
systemctl start nginx;
systemctl reload nginx;