apt update;
apt upgrade -y;
apt-get install lsb-release ca-certificates apt-transport-https software-properties-common -y;
add-apt-repository ppa:ondrej/php;
ufw allow OpenSSH;
ufw allow Postfix;
ufw allow 80;
ufw allow 8080;
ufw allow 3000;
ufw allow 443;
ufw allow 587;
echo "y" | ufw enable;
apt-get install -y mysql-server;
apt-get install -y php8.2;
apt-get install -y php8.2-cli;
apt-get install -y php8.2-fpm;
apt-get install -y php8.2-mysql;
apt-get install -y php8.2-curl;
apt-get install -y php8.2-mbstring;
apt-get install -y php8.2-mysql;
apt-get install -y php8.2-curl;
apt-get install -y php8.2-gd;
apt-get install -y php8.2-zip;
apt-get install -y php8.2-xml;
apt-get install -y net-tools;
apt-get install -y zip;
apt-get install -y unzip;
apt-get install -y p7zip-full;
apt-get install -y nginx;
apt-get install -y build-essential;
apt-get install -y curl;
apt-get install -y s3cmd;
apt-get install -y htop;
apt-get install -y poppler-utils;
apt-get install -y python3-pip;
apt-get install -y imagemagick;
apt-get install -y ffmpeg;
systemctl disable --now apache2;
systemctl reload nginx;
echo "ALTER USER 'mysql_root_user'@'localhost' IDENTIFIED WITH mysql_native_password BY 'mysql_root_pass'; FLUSH PRIVILEGES; exit;" | mysql;
curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php;
php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer;
snap install --classic certbot;
apt-get install -y python3-certbot-nginx;
echo 'post_max_size = 1024M' | tee -a /etc/php/8.2/fpm/php.ini;
echo 'upload_max_filesize = 1024M' | tee -a /etc/php/8.2/fpm/php.ini;
echo 'memory_limit = 2048M' | tee -a /etc/php/8.2/fpm/php.ini;
echo 'expire_logs_days = 3' | tee -a /etc/mysql/mysql.conf.d/mysqld.cnf;
/bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024;
/sbin/mkswap /var/swap.1;
/sbin/swapon /var/swap.1;
service php8.2-fpm restart;
apachectl stop;
apt-get update;